ECOLI_K=20

ecoli: ecoli_compare2.txt ecoli_compare2_nodn.txt ecoli-mapped.fq.gz.errhist \
	ecoli-reads.sam.errhist ecoli_compare4.txt \
	ecoli-mapped.fq.gz.subset.0.errhist \
	ecoli-mapped.fq.gz.subset.1.errhist \
	ecoli-mapped.fq.gz.subset.2.errhist \
	ecoli-mapped.fq.gz.subset.3.errhist \
	ecoli-mapped.fq.gz.subset.4.errhist \
	ecoli-mapped.fq.gz.errhist2

# bowtie index for ecoliMG1655.fa
ecoli.1.bt2: ecoliMG1655.fa
	bowtie2-build ecoliMG1655.fa ecoli
	samtools faidx ecoliMG1655.fa

# ecoli-reads.sam is the bowtie mapping of the reads to the reference genome.
ecoli-reads.sam: ecoli_ref-5m.fastq.gz ecoli.1.bt2
	./trim-at-N.py ecoli_ref-5m.fastq.gz | bowtie2 -p 4 -x ecoli -U - -S ecoli-reads.sam

# ecoli-reads.sam.pos is the 'pos' file containing the locations of mismatches,
# i.e. errors, determined from mapping.
ecoli-reads.sam.pos: ecoli-reads.sam
	./sam-scan.py ecoliMG1655.fa ecoli-reads.sam -o ecoli-reads.sam.pos

ecoli-mapped.fq.gz: ecoli_ref-5m.fastq.gz
	./extract-sam-seqs-to-fq.py ecoli-reads.sam ecoli_ref-5m.fastq.gz | gzip >& ecoli-mapped.fq.gz

# ecoli_ref.kh contains the counting table of k-mers in the raw read data set.
ecoli_ref.kh: ecoli-mapped.fq.gz
	load-into-counting.py ecoli_ref.kh -k $(ECOLI_K) -x 2e8 -N 4 ecoli-mapped.fq.gz --report-total-kmers

ecoli-reads-nodn.errors.pos: ecoli_ref.kh
	./report-errors-by-read.py -C 15 ecoli_ref.kh ecoli-mapped.fq.gz -o ecoli-reads-nodn.errors.pos

ecoli_compare2_nodn.txt: ecoli-reads-nodn.errors.pos
	./compare-pos.py ecoli-reads-nodn.errors.pos ecoli-reads.sam.pos ecoli-mapped.fq.gz > ecoli_compare2_nodn.txt

# ecoli_ref.dn.kh contains the counting table output by digital normalization
# of the raw E. coli reads.
ecoli_ref.dn.kh: ecoli-mapped.fq.gz
	normalize-by-median.py -x 1e8 -N 4 -k $(ECOLI_K) -C 20 -s ecoli_ref.dn.kh ecoli-mapped.fq.gz -R ecoli-dn-report.txt

# ecoli-reads.errors.pos contains the location of errors according to our
# own algorithm.
ecoli-reads.errors.pos: ecoli-mapped.fq.gz ecoli_ref.dn.kh
	./report-errors-by-read.py ecoli_ref.dn.kh ecoli-mapped.fq.gz -o ecoli-reads.errors.pos

# ecoli_compare2.txt: a comparison of the errors found by mapping and 
# those found by our k-mer spectral error detection implementation.
ecoli_compare2.txt: ecoli-reads.errors.pos ecoli-reads.sam.pos
	./compare-pos.py ecoli-reads.errors.pos ecoli-reads.sam.pos ecoli-mapped.fq.gz > ecoli_compare2.txt

ecoli-stream-mismatches.pos: ecoli-mapped.fq.gz
	./calc-errors-few-pass.py -x 1e8 -N 4 -k $(ECOLI_K) -Z 20 ecoli-mapped.fq.gz > ecoli-stream-mismatches.pos

ecoli_compare4.txt: ecoli-stream-mismatches.pos ecoli-reads.sam.pos
	./compare-pos.py ecoli-stream-mismatches.pos ecoli-reads.sam.pos ecoli-mapped.fq.gz > ecoli_compare4.txt

# ecoli-mapped.fq.gz.abundtrim contains the k-mer abundance trimmed
# reads, produced by trim-low-abund (streaming k-mer abundance trimming)
ecoli-mapped.fq.gz.abundtrim: ecoli-mapped.fq.gz
	$(KHMER)/sandbox/trim-low-abund.py -k $(ECOLI_K) -Z 20 -C 3 -x 1e8 -N 4 ecoli-mapped.fq.gz

# ecoli-abundtrim.sam is the mapping of the abundance-trimmed reads to the
# reference genome.
ecoli-abundtrim.sam: ecoli-mapped.fq.gz.abundtrim
	bowtie2 -p 4 -x ecoli -U ecoli-mapped.fq.gz.abundtrim -S ecoli-abundtrim.sam

# ecoli-abundtrim.sam.pos is the 'pos' file containing the locations of
# mismatches to the reference genome in the reads, based on mapping.
ecoli-abundtrim.sam.pos: ecoli-abundtrim.sam
	./sam-scan.py ecoliMG1655.fa ecoli-abundtrim.sam -o ecoli-abundtrim.sam.pos

# ecoli-report-untrim.txt - a report on the error rate of the untrimmed reads,
# based on mapping to the reference.
ecoli-report-untrim.txt: ecoli-reads.sam.pos ecoli-mapped.fq.gz
	./summarize-pos-file.py ecoli-reads.sam.pos ecoli-mapped.fq.gz > ecoli-report-untrim.txt

# ecoli-report-untrim.txt - a report on the error rate of the k-mer
# abundance trimmed reads, based on mapping to the reference.
ecoli-report-trim.txt: ecoli-abundtrim.sam.pos ecoli-mapped.fq.gz.abundtrim
	./summarize-pos-file.py ecoli-abundtrim.sam.pos ecoli-mapped.fq.gz.abundtrim > ecoli-report-trim.txt

ecoli-errfree-reads.fa: ecoliMG1655.fa
	$(NULLGRAPH)/make-reads.py -S 1 -e 0 -r 100 -C 100 ecoliMG1655.fa > ecoli-errfree-reads.fa

ecoli-errfree-report.txt: ecoli-errfree-reads.fa
	normalize-by-median.py -x 1e8 -N 4 -k $(ECOLI_K) -C 20 ecoli-errfree-reads.fa -R ecoli-errfree-report.txt

ecoli-mapped.fq.gz.errhist: ecoli-mapped.fq.gz
	-$(KHMER)/sandbox/calc-error-profile.py ecoli-mapped.fq.gz

ecoli-mapped.fq.gz.subset.0.errhist: ecoli-mapped.fq.gz.subset.0
	-$(KHMER)/sandbox/calc-error-profile.py ecoli-mapped.fq.gz.subset.0

ecoli-mapped.fq.gz.subset.1.errhist: ecoli-mapped.fq.gz.subset.1
	-$(KHMER)/sandbox/calc-error-profile.py ecoli-mapped.fq.gz.subset.1

ecoli-mapped.fq.gz.subset.2.errhist: ecoli-mapped.fq.gz.subset.2
	-$(KHMER)/sandbox/calc-error-profile.py ecoli-mapped.fq.gz.subset.2

ecoli-mapped.fq.gz.subset.3.errhist: ecoli-mapped.fq.gz.subset.3
	-$(KHMER)/sandbox/calc-error-profile.py ecoli-mapped.fq.gz.subset.3

ecoli-mapped.fq.gz.subset.4.errhist: ecoli-mapped.fq.gz.subset.4
	-$(KHMER)/sandbox/calc-error-profile.py ecoli-mapped.fq.gz.subset.4

ecoli-mapped.fq.gz.errhist2: ecoli-mapped.fq.gz ecoli_ref.dn.kh
	./report-errhist-2pass.py ecoli_ref.dn.kh ecoli-mapped.fq.gz  -o ecoli-mapped.fq.gz.errhist2

ecoli-reads.sam.errhist: ecoli-reads.sam ecoliMG1655.fa
	./sam-scan-errhist.py ecoliMG1655.fa ecoli-reads.sam -o ecoli-reads.sam.errhist

ecoli-counts.txt: ecoli-mapped.fq.gz ecoli_ref.dn.kh ecoli-mapped.fq.gz.keep
	$(KHMER)/sandbox/unique_kmers.py ecoli-mapped.fq.gz $(ECOLI_K) > ecoli-counts.txt
	$(KHMER)/sandbox/unique_kmers.py ecoli-mapped.fq.gz.keep $(ECOLI_K) >> ecoli-counts.txt

####

ecoli_corr: ecoli-mapped.raw.cor.fq.gz ecoli-mapped.dn.cor.fq.gz \
	quake-ecoli-raw-cor.txt quake-ecoli-dn-cor.txt

ecoli-mapped.dn.cor.fq.gz: ecoli-mapped.fq.gz ecoli-mapped.fq.gz.keep
	echo ecoli-mapped.fq.gz > ecoli_quake_list.txt
	ln -fs /usr/local/bin/jellyfish .
	cat ecoli-mapped.fq.gz.keep | $(QUAKE)/bin/count-qmers -q 33 -k 14 > ecoli_dn_counts.out
	$(QUAKE)/bin/cov_model.py ecoli_dn_counts.out > ecoli_dn_counts.cov
	$(QUAKE)/bin/correct -f ecoli_quake_list.txt -p 4 -k 14 -q 33 -c 7.94 -z -m ecoli_dn_counts.out
	mv ecoli-mapped.cor.fq.gz ecoli-mapped.dn.cor.fq.gz

ecoli-mapped.raw.cor.fq.gz: ecoli-mapped.fq.gz
	echo ecoli-mapped.fq.gz > ecoli_quake_list.txt
	ln -fs /usr/local/bin/jellyfish .
	gunzip -c ecoli-mapped.fq.gz | $(QUAKE)/bin/count-qmers -q 33 -k 14 > ecoli_raw_counts.out
	$(QUAKE)/bin/cov_model.py ecoli_raw_counts.out
	$(QUAKE)/bin/correct -f ecoli_quake_list.txt -p 4 -k 14 -q 33 -c 7.2 -z -m ecoli_raw_counts.out
	mv ecoli-mapped.cor.fq.gz ecoli-mapped.raw.cor.fq.gz

# ecoli-reads.dn.cor.sam is the bowtie mapping of the DN-Quake-corrected reads to the reference genome.
ecoli-reads.dn.cor.sam: ecoli_ref-5m.dn.cor.fastq.gz ecoli.1.bt2
	gunzip -c ecoli_ref-5m.dn.cor.fastq.gz | bowtie2 -p 4 -x ecoli -U - -S ecoli-reads.dn.cor.sam

# ecoli-reads.dn.cor.sam.pos is the 'pos' file containing the locations
# of mismatches from the dn quake-corrected reads.
ecoli-reads.dn.cor.sam.pos: ecoli-reads.dn.cor.sam
	./sam-scan.py ecoliMG1655.fa ecoli-reads.dn.cor.sam -o ecoli-reads.dn.cor.sam.pos

quake-ecoli-dn-cor.txt: ecoli-reads.dn.cor.sam.pos
	./summarize-pos-file.py ecoli-reads.dn.cor.sam.pos ecoli_ref-5m.dn.cor.fastq.gz > quake-ecoli-dn-cor.txt

# ecoli-reads.raw.cor.sam is the bowtie mapping of the Quake-corrected reads to the reference genome.
ecoli-reads.raw.cor.sam: ecoli_ref-5m.raw.cor.fastq.gz ecoli.1.bt2
	gunzip -c ecoli_ref-5m.raw.cor.fastq.gz | bowtie2 -p 4 -x ecoli -U - -S ecoli-reads.raw.cor.sam

# ecoli-reads.raw.cor.sam.pos is the 'pos' file containing the locations
# of mismatches from the raw quake-corrected reads.
ecoli-reads.raw.cor.sam.pos: ecoli-reads.raw.cor.sam
	./sam-scan.py ecoliMG1655.fa ecoli-reads.raw.cor.sam -o ecoli-reads.raw.cor.sam.pos

quake-ecoli-raw-cor.txt: ecoli-reads.raw.cor.sam.pos
	./summarize-pos-file.py ecoli-reads.raw.cor.sam.pos ecoli_ref-5m.raw.cor.fastq.gz > quake-ecoli-raw-cor.txt
