ECOLI_K=20

ecoli: ecoli-report.txt ecoli-report-nodn.txt ecoli-mapped.fq.gz.errhist

# bowtie index for ecoliMG1655.fa
ecoli.1.bt2: ecoliMG1655.fa
	bowtie2-build ecoliMG1655.fa ecoli
	samtools faidx ecoliMG1655.fa

# ecoli-reads.sam is the bowtie mapping of the reads to the reference genome.
ecoli-reads.sam: ecoli_ref-5m.fastq.gz ecoli.1.bt2
	gunzip -c ecoli_ref-5m.fastq.gz | bowtie2 -p 4 -x ecoli -U - -S ecoli-reads.sam

# ecoli-reads.sam.pos is the 'pos' file containing the locations of mismatches,
# i.e. errors, determined from mapping.
ecoli-reads.sam.pos: ecoli-reads.sam
	./sam-scan.py ecoliMG1655.fa ecoli-reads.sam -o ecoli-reads.sam.pos

ecoli-mapped.fq.gz: ecoli_ref-5m.fastq.gz
	./extract-sam-seqs-to-fq.py ecoli-reads.sam ecoli_ref-5m.fastq.gz | gzip >& ecoli-mapped.fq.gz

# ecoli_ref.kh contains the counting table of k-mers in the raw read data set.
ecoli_ref.kh: ecoli-mapped.fq.gz
	load-into-counting.py ecoli_ref.kh -k $(ECOLI_K) -x 2e8 -N 4 ecoli-mapped.fq.gz --report-total-kmers

ecoli-reads-nodn.errors.pos: ecoli_ref.kh
	./report-errors-by-read.py -C 15 ecoli_ref.kh ecoli-mapped.fq.gz -o ecoli-reads-nodn.errors.pos

ecoli-report-nodn.txt: ecoli-reads-nodn.errors.pos
	./compare-pos.py ecoli-reads-nodn.errors.pos ecoli-reads.sam.pos ecoli-mapped.fq.gz > ecoli-report-nodn.txt

# ecoli_ref.dn.kh contains the counting table output by digital normalization
# of the raw E. coli reads.
ecoli_ref.dn.kh: ecoli-mapped.fq.gz
	normalize-by-median.py -x 1e8 -N 4 -k $(ECOLI_K) -C 20 -s ecoli_ref.dn.kh ecoli-mapped.fq.gz -R ecoli-dn-report.txt

# ecoli-reads.errors.pos contains the location of errors according to our
# own algorithm.
ecoli-reads.errors.pos: ecoli-mapped.fq.gz ecoli_ref.dn.kh
	./report-errors-by-read.py ecoli_ref.dn.kh ecoli-mapped.fq.gz -o ecoli-reads.errors.pos

# ecoli-report.txt: a comparison of the errors found by mapping and 
# those found by our k-mer spectral error detection implementation.
ecoli-report.txt: ecoli-reads.errors.pos ecoli-reads.sam.pos
	./compare-pos.py ecoli-reads.errors.pos ecoli-reads.sam.pos ecoli-mapped.fq.gz > ecoli-report.txt

ecoli-stream-mismatches.pos: ecoli-mapped.fq.gz
	./calc-errors-few-pass.py -x 1e8 -N 4 -k $(ECOLI_K) -Z 20 ecoli-mapped.fq.gz > ecoli-stream-mismatches.pos

ecoli-stream-report.txt: ecoli-stream-mismatches.pos ecoli-reads.sam.pos
	./compare-pos.py ecoli-stream-mismatches.pos ecoli-reads.sam.pos ecoli-mapped.fq.gz > ecoli-stream-report.txt

# ecoli-mapped.fq.gz.abundtrim contains the k-mer abundance trimmed
# reads, produced by trim-low-abund (streaming k-mer abundance trimming)
ecoli-mapped.fq.gz.abundtrim: ecoli-mapped.fq.gz
	$(KHMER)/sandbox/trim-low-abund.py -k $(ECOLI_K) -Z 20 -C 5 -x 1e8 -N 4 ecoli-mapped.fq.gz

# ecoli-abundtrim.sam is the mapping of the abundance-trimmed reads to the
# reference genome.
ecoli-abundtrim.sam: ecoli-mapped.fq.gz.abundtrim
	bowtie2 -p 4 -x ecoli -U ecoli-mapped.fq.gz.abundtrim -S ecoli-abundtrim.sam

# ecoli-abundtrim.sam.pos is the 'pos' file containing the locations of
# mismatches to the reference genome in the reads, based on mapping.
ecoli-abundtrim.sam.pos: ecoli-abundtrim.sam
	./sam-scan.py ecoliMG1655.fa ecoli-abundtrim.sam -o ecoli-abundtrim.sam.pos

# ecoli-report-untrim.txt - a report on the error rate of the untrimmed reads,
# based on mapping to the reference.
ecoli-report-untrim.txt: ecoli-reads.sam.pos ecoli-mapped.fq.gz
	./summarize-pos-file.py ecoli-reads.sam.pos ecoli-mapped.fq.gz > ecoli-report-untrim.txt

# ecoli-report-untrim.txt - a report on the error rate of the k-mer
# abundance trimmed reads, based on mapping to the reference.
ecoli-report-trim.txt: ecoli-abundtrim.sam.pos ecoli-mapped.fq.gz.abundtrim
	./summarize-pos-file.py ecoli-abundtrim.sam.pos ecoli-mapped.fq.gz.abundtrim > ecoli-report-trim.txt

ecoli-errfree-reads.fa: ecoliMG1655.fa
	$(NULLGRAPH)/make-reads.py -S 1 -e 0 -r 100 -C 100 ecoliMG1655.fa > ecoli-errfree-reads.fa

ecoli-errfree-report.txt: ecoli-errfree-reads.fa
	normalize-by-median.py -x 1e8 -N 4 -k $(ECOLI_K) -C 20 ecoli-errfree-reads.fa -R ecoli-errfree-report.txt

ecoli-mapped.fq.gz.errhist: ecoli-mapped.fq.gz
	-$(KHMER)/sandbox/calc-error-profile.py ecoli-mapped.fq.gz

ecoli-reads.sam.errhist: ecoli-reads.sam ecoliMG1655.fa
	./sam-scan-errhist.py ecoliMG1655.fa ecoli-reads.sam -o ecoli-reads.sam.errhist

ecoli-counts.txt: ecoli-mapped.fq.gz ecoli_ref.dn.kh ecoli-mapped.fq.gz.keep
	$(KHMER)/sandbox/unique_kmers.py ecoli-mapped.fq.gz $(ECOLI_K) > ecoli-counts.txt
	$(KHMER)/sandbox/unique_kmers.py ecoli-mapped.fq.gz.keep $(ECOLI_K) >> ecoli-counts.txt