simple-mrna-reads.fa: simple-mrna.fa
	$(NULLGRAPH)/make-biased-reads.py -S 1 -e .01 -r 100 -C 100 simple-mrna.fa --mutation-details simple-mrna-reads.mut > simple-mrna-reads.fa

simple-mrna-reads.mut.pos: simple-mrna-reads.fa
	./convert-mut-to-pos.py simple-mrna-reads.mut simple-mrna-reads.mut.pos

simple-mrna-reads.dn.kh: simple-mrna-reads.fa
	normalize-by-median.py -k 20 -C 20 simple-mrna-reads.fa -s simple-mrna-reads.dn.kh -x 2e6 -N 4

simple-mrna-errors.pos: simple-mrna-reads.dn.kh
	./report-errors-by-read.py -V --coverage 20 simple-mrna-reads.dn.kh simple-mrna-reads.fa -o simple-mrna-errors.pos

simple-mrna-reads.sam: simple-mrna-reads.fa
	bowtie2-build simple-mrna.fa simple-mrna > /dev/null
	samtools faidx simple-mrna.fa

	bowtie2 -f -x simple-mrna -U simple-mrna-reads.fa -S simple-mrna-reads.sam

simple-mrna-reads.sorted.bam: simple-mrna-reads.sam
	samtools import simple-mrna.fa.fai simple-mrna-reads.sam simple-mrna-reads.bam
	samtools sort simple-mrna-reads.bam simple-mrna-reads.sorted
	samtools index simple-mrna-reads.sorted.bam

simple-mrna-sam-mismatches.pos: simple-mrna-reads.sam
	./sam-scan.py simple-mrna.fa simple-mrna-reads.sam -o simple-mrna-sam-mismatches.pos

simple-mrna-reads.fa.abundtrim: simple-mrna-reads.fa
	$(KHMER)/sandbox/trim-low-abund.py -V -k 20 -Z 20 -C 3 simple-mrna-reads.fa

simple-mrna-abundtrim.sam: simple-mrna-reads.fa.abundtrim \
	simple-mrna-reads.sam
	bowtie2 -f -x simple-mrna -U simple-mrna-reads.fa.abundtrim -S simple-mrna-abundtrim.sam

simple-mrna-abundtrim-sam-mismatches.pos: simple-mrna-abundtrim.sam
	./sam-scan.py simple-mrna.fa simple-mrna-abundtrim.sam -o simple-mrna-abundtrim-sam-mismatches.pos

rcompare: simple-mrna-errors.pos simple-mrna-sam-mismatches.pos
	./compare-pos.py simple-mrna-errors.pos simple-mrna-sam-mismatches.pos simple-mrna-reads.fa

rcompare2: simple-mrna-errors.pos simple-mrna-reads.mut.pos
	./compare-pos.py -V simple-mrna-errors.pos simple-mrna-reads.mut.pos simple-mrna-reads.fa

rcompare3: simple-mrna-sam-mismatches.pos simple-mrna-reads.mut.pos
	./compare-pos.py simple-mrna-sam-mismatches.pos simple-mrna-reads.mut.pos simple-mrna-reads.fa

simple-mrna-stream-mismatches.pos: simple-mrna-reads.fa
	./calc-errors-few-pass.py -V simple-mrna-reads.fa > simple-mrna-stream-mismatches.pos

rcompare4: simple-mrna-stream-mismatches.pos simple-mrna-reads.mut.pos
	./compare-pos.py -V simple-mrna-stream-mismatches.pos simple-mrna-reads.mut.pos simple-mrna-reads.fa

rcompare5: simple-mrna-sam-mismatches.pos simple-mrna-abundtrim-sam-mismatches.pos
	./summarize-pos-file.py simple-mrna-sam-mismatches.pos simple-mrna-reads.fa
	./summarize-pos-file.py simple-mrna-abundtrim-sam-mismatches.pos simple-mrna-reads.fa.abundtrim
