rseq: rseq_compare2 rseq_compare4 rseq_compare5

rseq_compare2: rseq_compare2.txt
	cat rseq_compare2.txt

rseq_compare2.txt: rseq-errors.pos rseq-sam-mismatches.pos
	./compare-pos.py -V rseq-errors.pos rseq-sam-mismatches.pos rseq-reads.fq.gz > rseq_compare2.txt

rseq-reads.fq.gz: mouse-5m.fq.gz
	gunzip -c mouse-5m.fq.gz | head -4000000 | gzip -9c > rseq-reads.fq.gz

rseq-errors.pos: rseq-reads.dn.kh
	./report-errors-by-read.py -V --coverage 20 rseq-reads.dn.kh rseq-reads.fq.gz > rseq-errors.pos

rseq-reads.dn.kh: rseq-reads.fq.gz
	normalize-by-median.py -k 20 -C 20 rseq-reads.fq.gz -s rseq-reads.dn.kh -x 1e8 -N 4

rseq.1.ebwt: rna.fa
	bowtie-build rna.fa rseq > /dev/null
	samtools faidx rna.fa

rseq-reads.sam: rseq-reads.fq.gz rseq.1.ebwt

	gunzip -c rseq-reads.fq.gz | bowtie rseq -q - -S rseq-reads.sam

rseq-sam-mismatches.pos: rseq-reads.sam
	./sam-scan.py rna.fa rseq-reads.sam > rseq-sam-mismatches.pos

rseq-stream-mismatches.pos: rseq-reads.fq.gz
	./calc-errors-few-pass.py -V rseq-reads.fq.gz -x 1e8 -N 4 > rseq-stream-mismatches.pos

rseq_compare4.txt: rseq-stream-mismatches.pos rseq-sam-mismatches.pos
	./compare-pos.py -V rseq-stream-mismatches.pos rseq-sam-mismatches.pos rseq-reads.fq.gz > rseq_compare4.txt

rseq_compare4: rseq_compare4.txt
	cat rseq_compare4.txt

rseq_compare5.txt: rseq-sam-mismatches.pos rseq-abundtrim-sam-mismatches.pos
	./summarize-pos-file.py rseq-sam-mismatches.pos rseq-reads.fq.gz > rseq_compare5.txt
	./summarize-pos-file.py rseq-abundtrim-sam-mismatches.pos rseq-reads.fq.gz.abundtrim >> rseq_compare5.txt

rseq_compare5: rseq_compare5.txt
	cat rseq_compare5.txt

rseq-reads.fq.gz.abundtrim: rseq-reads.fq.gz
	$(KHMER)/sandbox/trim-low-abund.py -V -k 20 -Z 20 -C 3 -x 1e8 -N 4 rseq-reads.fq.gz

rseq-abundtrim.sam: rseq-reads.fq.gz.abundtrim \
	rseq-reads.sam
	bowtie rseq -q rseq-reads.fq.gz.abundtrim -S rseq-abundtrim.sam

rseq-abundtrim-sam-mismatches.pos: rseq-abundtrim.sam
	./sam-scan.py rna.fa rseq-abundtrim.sam > rseq-abundtrim-sam-mismatches.pos

