PODAR_COV=20

podar:  podar.1.bt2 \
	podar_compare2.txt podar_compare4.txt podar_compare5 podar_compare5b

podar.1.bt2: podar-ref.fa
	bowtie2-build podar-ref.fa podar
	samtools faidx podar-ref.fa

podar-reads.sam: podar-1.fastq.gz podar.1.bt2
	./trim-at-N.py podar-1.fastq.gz | head -80000000 | bowtie2 -p 4 -x podar -U - -S podar-reads.sam

podar-mapped.fq.gz: podar-reads.sam
	./extract-sam-seqs-to-fq.py podar-reads.sam podar-1.fastq.gz | gzip > podar-mapped.fq.gz

podar-reads.sam.pos: podar-reads.sam
	./sam-scan.py podar-ref.fa podar-reads.sam > podar-reads.sam.pos

podar.dn.kh: podar-mapped.fq.gz
	 normalize-by-median.py -x 4e8 -N 4 -k 20 -C $(PODAR_COV) -s podar.dn.kh podar-mapped.fq.gz -R podar-dn-report.txt

podar-reads.errors.pos: podar-mapped.fq.gz podar.dn.kh
	 ./report-errors-by-read.py -V --coverage $(PODAR_COV) podar.dn.kh podar-mapped.fq.gz > podar-reads.errors.pos

podar_compare2.txt: podar-reads.errors.pos podar-reads.sam.pos
	./compare-pos.py -V podar-reads.errors.pos podar-reads.sam.pos podar-mapped.fq.gz > podar_compare2.txt

podar-stream-mismatches.pos: podar-mapped.fq.gz
	./calc-errors-few-pass.py -V -x 4e8 -N 4 -k 20 -Z $(PODAR_COV) podar-mapped.fq.gz > podar-stream-mismatches.pos

podar_compare4.txt: podar-stream-mismatches.pos podar-reads.sam.pos
	./compare-pos.py -V podar-stream-mismatches.pos podar-reads.sam.pos podar-mapped.fq.gz > podar_compare4.txt

podar-mapped.fq.gz.abundtrim: podar-mapped.fq.gz
	$(KHMER)/sandbox/trim-low-abund.py -V -k 20 -Z $(PODAR_COV) -C 3 -x 4e8 -N 4 podar-mapped.fq.gz

podar-abundtrim.sam: podar-mapped.fq.gz.abundtrim
	bowtie2 -p 4 -x podar -U podar-mapped.fq.gz.abundtrim -S podar-abundtrim.sam

podar-abundtrim.sam.pos: podar-abundtrim.sam
	./sam-scan.py podar-ref.fa podar-abundtrim.sam > podar-abundtrim.sam.pos

podar_compare5_pre.txt: podar-reads.sam.pos podar-mapped.fq.gz
	./summarize-pos-file.py podar-reads.sam.pos podar-mapped.fq.gz > podar_compare5_pre.txt

podar_compare5_post.txt: podar-abundtrim.sam.pos podar-mapped.fq.gz.abundtrim
	./summarize-pos-file.py podar-abundtrim.sam.pos podar-mapped.fq.gz.abundtrim > podar_compare5_post.txt

podar_compare5: podar_compare5_pre.txt podar_compare5_post.txt
	cat podar_compare5_pre.txt podar_compare5_post.txt

podar-reads.hicov.fq: podar-mapped.fq.gz podar.dn.kh
	$(KHMER)/sandbox/slice-reads-by-coverage.py -m $(PODAR_COV) podar.dn.kh podar-mapped.fq.gz podar-reads.hicov.fq

podar-reads.hicov.fq.keep: podar-reads.hicov.fq
	normalize-by-median.py -k 20 -C $(PODAR_COV) -x 1e8 -N 4 podar-reads.hicov.fq -s podar-reads.hicov.fq.dn.kh

podar-reads.hicov.fq.keep.hist: podar-reads.hicov.fq.keep
	abundance-dist.py -s podar-reads.hicov.fq.dn.kh podar-reads.hicov.fq.keep podar-reads.hicov.fq.keep.hist

podar-reads.hicov.fq.sam: podar-reads.hicov.fq podar.1.bt2
	bowtie2 -p 4 -x podar -U podar-reads.hicov.fq -S podar-reads.hicov.fq.sam

podar-reads-hicov-sam-mismatches.pos: podar-reads.hicov.fq.sam
	./sam-scan.py podar-ref.fa podar-reads.hicov.fq.sam -o podar-reads-hicov-sam-mismatches.pos

podar-reads-hicov-sam-mismatches-report.txt: podar-reads-hicov-sam-mismatches.pos
	./summarize-pos-file.py podar-reads-hicov-sam-mismatches.pos podar-reads.hicov.fq > podar-reads-hicov-sam-mismatches-report.txt

podar-reads.hicov.fq.sam.covdict: podar-reads.hicov.fq.sam
	./sam-scan-to-coverage-dict.py podar-ref.fa podar-reads.hicov.fq.sam podar-reads.hicov.fq.sam.covdict podar-reads.hicov.fq.sam.covhist

podar-reads.hicov.fq.abundtrim: podar-reads.hicov.fq
	$(KHMER)/sandbox/trim-low-abund.py -V -k 20 -C $(PODAR_COV) -C 3 -x 1e8 -N 4 podar-reads.hicov.fq

podar-hicov-abundtrim.sam: podar-reads.hicov.fq.abundtrim
	bowtie2 -p 4 -x podar -U podar-reads.hicov.fq.abundtrim -S podar-hicov-abundtrim.sam

podar-hicov-abundtrim.sam.pos: podar-hicov-abundtrim.sam
	./sam-scan.py podar-ref.fa podar-hicov-abundtrim.sam -o podar-hicov-abundtrim.sam.pos

podar_compare5b_pre.txt: podar-reads-hicov-sam-mismatches.pos podar-reads.hicov.fq
	./summarize-pos-file.py podar-reads-hicov-sam-mismatches.pos podar-reads.hicov.fq > podar_compare5b_pre.txt

podar_compare5b_post.txt: podar-hicov-abundtrim.sam.pos podar-reads.hicov.fq.abundtrim
	./summarize-pos-file.py podar-hicov-abundtrim.sam.pos podar-reads.hicov.fq.abundtrim > podar_compare5b_post.txt

podar_compare5b: podar_compare5b_pre.txt podar_compare5b_post.txt
	cat podar_compare5b_pre.txt podar_compare5b_post.txt
