simple-genome.fa:
	$(NULLGRAPH)/make-random-genome.py -l 1000 -s 1 > simple-genome.fa

simple-genome-reads.fa: simple-genome.fa
	$(NULLGRAPH)/make-reads.py -S 1 -e .01 -r 100 -C 100 simple-genome.fa --mutation-details simple-genome-reads.mut > simple-genome-reads.fa

simple-genome-kmers.hist: simple-genome.fa
	abundance-dist-single.py -s -k 20 simple-genome-reads.fa simple-genome-kmers.hist

simple-genome-dn-kmers.hist: simple-genome-reads.dn.kh
	abundance-dist-single.py -s -k 20 simple-genome-reads.fa.keep simple-genome-dn-kmers.hist

simple-genome-reads-even.fa: simple-genome.fa
	$(NULLGRAPH)/make-reads.py -S 1 -e .01 -r 100 -C 100 simple-genome.fa --mutation-details simple-genome-reads-even.mut --even > simple-genome-reads-even.fa

simple-genome-perfect.fa: simple-genome.fa
	$(NULLGRAPH)/make-reads.py -S 2 -e 0 -r 100 -C 100 simple-genome.fa > simple-genome-perfect.fa

simple-genome-reads.mut.pos: simple-genome-reads.fa
	./convert-mut-to-pos.py simple-genome-reads.mut simple-genome-reads.mut.pos

simple-genome-reads.kh: simple-genome-reads.fa
	load-into-counting.py simple-genome-reads.kh -k 20 -x 2e6 -N 4 simple-genome-reads.fa --report-total-kmers

simple-genome-errors-nodn.pos: simple-genome-reads.kh
	./report-errors-by-read.py -C 15 simple-genome-reads.kh simple-genome-reads.fa > simple-genome-errors-nodn.pos

simple-genome-reads.dn.kh: simple-genome-reads.fa
	normalize-by-median.py -k 20 -C 20 simple-genome-reads.fa -s simple-genome-reads.dn.kh -x 2e6 -N 4 -R simple-genome.report

simple-genome-errors.pos: simple-genome-reads.dn.kh
	./report-errors-by-read.py simple-genome-reads.dn.kh simple-genome-reads.fa > simple-genome-errors.pos

simple-genome-reads.sam: simple-genome-reads.fa
	bowtie-build simple-genome.fa simple-genome > /dev/null
	samtools faidx simple-genome.fa

	bowtie simple-genome -f simple-genome-reads.fa -S simple-genome-reads.sam

simple-genome-reads-even.sam: simple-genome-reads-even.fa
	bowtie-build simple-genome.fa simple-genome > /dev/null
	samtools faidx simple-genome.fa

	bowtie simple-genome -f simple-genome-reads-even.fa -S simple-genome-reads-even.sam

simple-genome-reads-even.sam.errhist: simple-genome-reads-even.sam
	./sam-scan-errhist.py simple-genome.fa simple-genome-reads-even.sam > simple-genome-reads-even.sam.errhist

simple-genome-reads.sorted.bam: simple-genome-reads.sam
	samtools import simple-genome.fa.fai simple-genome-reads.sam simple-genome-reads.bam
	samtools sort simple-genome-reads.bam simple-genome-reads.sorted
	samtools index simple-genome-reads.sorted.bam

simple-genome-sam-mismatches.pos: simple-genome-reads.sam
	./sam-scan.py simple-genome.fa simple-genome-reads.sam > simple-genome-sam-mismatches.pos

simple-genome-reads.covdict: simple-genome-reads.sam
	./sam-scan-to-coverage-dict.py simple-genome.fa simple-genome-reads.sam simple-genome-reads.covdict simple-genome-reads.covhist

simple-genome-reads.fa.abundtrim: simple-genome-reads.fa
	$(KHMER)/sandbox/trim-low-abund.py -k 20 -Z 20 -C 5 simple-genome-reads.fa

simple-genome-abundtrim.sam: simple-genome-reads.fa.abundtrim \
	simple-genome-reads.sam
	bowtie simple-genome -f simple-genome-reads.fa.abundtrim -S simple-genome-abundtrim.sam

simple-genome-abundtrim-sam-mismatches.pos: simple-genome-abundtrim.sam
	./sam-scan.py simple-genome.fa simple-genome-abundtrim.sam > simple-genome-abundtrim-sam-mismatches.pos

compare: simple-genome-errors.pos simple-genome-sam-mismatches.pos
	./compare-pos.py simple-genome-errors.pos simple-genome-sam-mismatches.pos simple-genome-reads.fa

compare2: simple-genome-errors.pos simple-genome-reads.mut.pos
	./compare-pos.py simple-genome-errors.pos simple-genome-reads.mut.pos simple-genome-reads.fa

compare3: simple-genome-sam-mismatches.pos simple-genome-reads.mut.pos
	./compare-pos.py simple-genome-sam-mismatches.pos simple-genome-reads.mut.pos simple-genome-reads.fa

simple-genome-stream-mismatches.pos: simple-genome-reads.fa
	./calc-errors-few-pass.py -k 20 -x 2e6 -Z 20 simple-genome-reads.fa > simple-genome-stream-mismatches.pos

compare4: simple-genome-stream-mismatches.pos simple-genome-reads.mut.pos
	./compare-pos.py simple-genome-stream-mismatches.pos simple-genome-reads.mut.pos simple-genome-reads.fa

compare5: simple-genome-sam-mismatches.pos simple-genome-abundtrim-sam-mismatches.pos
	./summarize-pos-file.py simple-genome-sam-mismatches.pos simple-genome-reads.fa
	./summarize-pos-file.py simple-genome-abundtrim-sam-mismatches.pos simple-genome-reads.fa.abundtrim

simple-genome-reads-even.fa.errhist: simple-genome-reads-even.fa
	-$(KHMER)/sandbox/calc-error-profile.py simple-genome-reads-even.fa

compare6: simple-genome-reads.mut.pos simple-genome-errors-nodn.pos
	./compare-pos.py simple-genome-errors-nodn.pos simple-genome-reads.mut.pos simple-genome-reads.fa

simple-genome-reads.cor.sam: simple-genome-reads.cor.fq
	bowtie-build simple-genome.fa simple-genome > /dev/null
	samtools faidx simple-genome.fa

	bowtie simple-genome -q simple-genome-reads.cor.fq -S simple-genome-reads.cor.sam

simple-genome-sam-cor-mismatches.pos: simple-genome-reads.cor.sam
	./sam-scan.py simple-genome.fa simple-genome-reads.cor.sam > simple-genome-sam-cor-mismatches.pos
	./compare-pos.py simple-genome-errors.pos simple-genome-sam-cor-mismatches.pos simple-genome-reads.fa
