#---------------------------------------------------------------------
cpodar-combined: cpodar-reads.sam \
	cpodar-mapped.fq.gz \
	cpodar-reads.sam.pos \
	cpodar-mapped.fq.gz.abundtrim \
	cpodar-compare5-pre.txt \
	cpodar-abundtrim.sam \
	cpodar-abundtrim.sam.pos \
	cpodar-compare5-post.txt

cmouse-combined: cmouse-reads.sam \
	cmouse-mapped.fq.gz \
	cmouse-reads.sam.pos \
	cmouse-mapped.fq.gz.abundtrim \
	cmouse-compare5-pre.txt \
	cmouse-abundtrim.sam \
	cmouse-abundtrim.sam.pos \
	cmouse-compare5-post.txt

#--------------------------------------Podar Work--------------------

cpodar-reads.sam: podar.1.bt2
	./trim-at-N.py cpodar.fastq.gz | bowtie2 -p 4 -x podar -U - -S cpodar-reads.sam

cpodar-mapped.fq.gz: cpodar.fastq.gz cpodar-reads.sam
	./extract-sam-seqs-to-fq.py cpodar-reads.sam cpodar.fastq.gz | gzip -9c > cpodar-mapped.fq.gz

cpodar-reads.sam.pos: cpodar-reads.sam podar-ref.fa
	./sam-scan.py podar-ref.fa cpodar-reads.sam > cpodar-reads.sam.pos

cpodar-mapped.fq.gz.abundtrim: cpodar-mapped.fq.gz
	$(KHMER)/sandbox/trim-low-abund.py -V -k 20 -Z 20 -C 3 -x 2e9 -N 4 cpodar-mapped.fq.gz

cpodar-compare5-pre.txt: cpodar-mapped.fq.gz
	./summarize-pos-file.py cpodar-reads.sam.pos cpodar-mapped.fq.gz > cpodar-compare5-pre.txt

cpodar-abundtrim.sam: cpodar-mapped.fq.gz.abundtrim
	bowtie2 -p 4 -x podar -U cpodar-mapped.fq.gz.abundtrim -S cpodar-abundtrim.sam

cpodar-abundtrim.sam.pos: cpodar-abundtrim.sam
	./sam-scan.py podar-ref.fa cpodar-abundtrim.sam > cpodar-abundtrim.sam.pos

cpodar-compare5-post.txt: cpodar-abundtrim.sam.pos cpodar-mapped.fq.gz.abundtrim
	./summarize-pos-file.py cpodar-abundtrim.sam.pos cpodar-mapped.fq.gz.abundtrim > cpodar-compare5-post.txt


#---------------------------------------Mouse  Work--------------

cmouse-reads.sam: rseq.1.bt2
	./trim-at-N.py cmouse.fastq.gz | bowtie2 -p 4 -x rseq -U - -S cmouse-reads.sam

cmouse-mapped.fq.gz: cmouse.fastq.gz cmouse-reads.sam
	./extract-sam-seqs-to-fq.py cmouse-reads.sam cmouse.fastq.gz | gzip -9c > cmouse-mapped.fq.gz

cmouse-reads.sam.pos: cmouse-reads.sam rna.fa
	./sam-scan.py rna.fa cmouse-reads.sam > cmouse-reads.sam.pos

cmouse-mapped.fq.gz.abundtrim: cmouse-mapped.fq.gz
	$(KHMER)/sandbox/trim-low-abund.py -V -k 20 -Z 20 -C 3 -x 4e8 -N 4 cmouse-mapped.fq.gz

cmouse-compare5-pre.txt: cmouse-mapped.fq.gz
	./summarize-pos-file.py cmouse-reads.sam.pos cmouse-mapped.fq.gz > cmouse-compare5-pre.txt

cmouse-abundtrim.sam: cmouse-mapped.fq.gz.abundtrim
	bowtie2 -p 4 -x rseq -U cmouse-mapped.fq.gz.abundtrim -S cmouse-abundtrim.sam

cmouse-abundtrim.sam.pos: cmouse-abundtrim.sam
	./sam-scan.py rna.fa cmouse-abundtrim.sam > cmouse-abundtrim.sam.pos

cmouse-compare5-post.txt: cmouse-abundtrim.sam.pos cmouse-mapped.fq.gz.abundtrim
	./summarize-pos-file.py cmouse-abundtrim.sam.pos cmouse-mapped.fq.gz.abundtrim > cmouse-compare5-post.txt
